#!/bin/sh

source /etc/preinit
script_init

countryCode="eur_gr"
language="Greek"
echo "   ___             _   "
echo "  / __|_ _ ___ ___| |__"
echo " | (_ | '_/ -_) -_) / /"
echo "  \\___|_| \\___\\___|_\\_\\"
echo ""
echo "$language Translation: ThanosRD"
echo ""
echo "Checking localization files."
customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu/customlangs"
addonPath="$mountpoint/etc/options_menu/languages"
scriptPath="$addonPath/scripts"
customLangDir="$addonPath/custom_languages"

cd "$addonPath" || exit

wget -q --spider "$customLangURL"/snes$countryCode.tar.gz

if [ $? -eq 0 ]; then
	echo "Downloading..."
	wget "$customLangURL"/snes$countryCode.tar.gz

	echo "Unpacking language..."
	tar -xzf snes$countryCode.tar.gz && rm -f ./*.tar.gz
	echo "Checking for $countryCode font support..."
	if [ ! -d "$customLangDir/fonts" ]; then
		cd "$customLangDir" || exit
		wget "$customLangURL"/fonts.tar.gz
		tar -xzf fonts.tar.gz && rm -f ./*.tar.gz
	fi

touch "$addonPath/commands/c0000_separator"

    echo "COMMAND_NAME=Translate to $language
COMMAND_TYPE=INTERNAL
RESTART_UI=FALSE
COMMAND_STR=sh $scriptPath/$countryCode && usleep 50000 && hakchi reboot
PREVIEW_IMAGE=$customLangDir/$countryCode.png
PREVIEW_IMAGE_X=590
PREVIEW_IMAGE_Y=248" >"$addonPath/commands/c0008_$countryCode"

sed -r "s/COUNTRYCODEHERE/${countryCode}/g;s/LANGUAGEHERE/${language}/g;" "$scriptPath/_template" >"$scriptPath/$countryCode"

	sleep 2
	echo "Complete."
	echo "Custom language now available and ready to use from the list."
else
	echo "Something may be wrong here."
	echo "Could not find the selected theme,"
	echo "check your internet connection. "
fi
