#!/bin/sh
source /etc/preinit
script_init


echo "  ___ _                        _                                        _  _         _   "
echo " / __| |_  ___ _ _  ___ _ _   | |   __ _ _ _  __ _ _  _ __ _ __ _ ___  | || |__ _ __| |__"
echo " \\__ \\ ' \\/ _ \\ ' \\/ -_) ' \\  | |__/ _\` | ' \\/ _\` | || / _\` / _\` / -_) | __ / _\` / _| / /"
echo " |___/_||_\\___/_||_\\___|_||_| |____\\__,_|_||_\\__, |\\_,_\\__,_\\__, \\___| |_||_\\__,_\\__|_\\_\\"
echo "                                             |___/          |___/                        "
echo ""
echo "HMOD by: Advokaten"
echo "Options Menu Scripts: DefKorns"
echo ""
echo "Traduciendo al Espanol, por favor espere ..."

countryCode="eur_es"
optionsDir="$mountpoint/etc/options_menu/languages"
commandsDir="$optionsDir/shonen/commands"
# [ -f "$preinitpath/b8024_themeselector" ] && rm -f "$preinitpath/b8024_themeselector"
# [ -f "$preinitpath/p8024_themeselector" ] && rm -f "$preinitpath/p8024_themeselector"
sed -r "s/CHANGE_ME/${countryCode}/g;" "$optionsDir/scripts/shonen_hack" >"$preinitpath/p8024_zlanguage"

customFont="$mountpoint/media/$modname/fonts"
	[ ! -d "$customFont" ] && customFont="$rootfs/usr/share/fonts"

if [ ! -f "$customFont/copyright.fnt" ]; then

cd "$optionsDir/fonts" && find . -iname "*.fnt" -exec cp -r {} "$customFont" \;

fi

actiVe="$(grep -F " [X]" $commandsDir/* | cut -d : -f 1)"

if [ -f "$actiVe" ]; then
	sed -r -i 's/ \[X\]//g' $actiVe
	sed -r -i "1 s|$| [X]|" "$commandsDir/c0002_$countryCode"
else
	sed -r -i "1 s|$| [X]|" "$commandsDir/c0002_$countryCode"
fi
sleep 2
