#!/bin/sh
source /etc/preinit
script_init

echo "  ___ _                        _                                        _  _         _   "
echo " / __| |_  ___ _ _  ___ _ _   | |   __ _ _ _  __ _ _  _ __ _ __ _ ___  | || |__ _ __| |__"
echo " \\__ \\ ' \\/ _ \\ ' \\/ -_) ' \\  | |__/ _\` | ' \\/ _\` | || / _\` / _\` / -_) | __ / _\` / _| / /"
echo " |___/_||_\\___/_||_\\___|_||_| |____\\__,_|_||_\\__, |\\_,_\\__,_\\__, \\___| |_||_\\__,_\\__|_\\_\\"
echo "                                             |___/          |___/                        "
echo ""
echo "HMOD by: Advokaten"
echo "Options Menu Scripts: DefKorns"
echo ""
echo "Uninstalling..."
rm -f "$mountpoint/etc/preinit.d/p8024_zlanguage"
optionsDir="$mountpoint/etc/options_menu/languages"
commandsDir="$optionsDir/shonen/commands"

customFont="$mountpoint/media/$modname/fonts"
	[ ! -d "$customFont" ] && customFont="$rootfs/usr/share/fonts"

cd "$customFont" && find . -type f -not -name 'title.*' -print0 -exec rm {} \;
[ -f "$customFont/title.backup" ] && cp -r "$customFont/title.backup" "$customFont/title.fnt" && rm -f "$customFont/title.backup"

actiVe="$(grep -F " [X]" $commandsDir/* | cut -d : -f 1)"

if [ -f "$actiVe" ]; then
	sed -r -i 's/ \[X\]//g' $actiVe
fi
sleep 2
