#!/bin/sh

source /etc/preinit
script_init
#customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu/customlangs"
customLangURL="https://github.com/DefKorns/OM_Shonen_Language-Hack/releases/download/RC"
addonPath="$mountpoint/etc/options_menu/shonen"
countryCode="eur_nor"

cd "$addonPath"

echo "  _  _                         _           "
echo " | \\| |___ _ ___ __ _____ __ _(_)__ _ _ _  "
echo " | .\` / _ \\ '_\\ V  V / -_) _\` | / _\` | ' \\ "
echo " |_|\\_\\___/_|  \\_/\\_/\\___\\__, |_\\__,_|_||_|"
echo "                         |___/             "
echo ""
echo "Translation: Chinspanker"
echo "Shonen Convertion: DefKorns"
echo ""
echo "Checking localization files."
wget -q --spider "$customLangURL"/$countryCode.tar.gz

if [ $? -eq 0 ]; then
echo "Downloading..."
wget "$customLangURL"/$countryCode.tar.gz

echo "Installing language..."
	tar -xzvf $countryCode.tar.gz && rm -f ./*.tar.gz
    sleep 2
	echo "Installation complete."
else
   echo "Something may be wrong here."
   echo "Could not find the selected theme,"
   echo "check your internet connection. "
fi