#!/bin/sh

source /etc/preinit
script_init
customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu/customlangs"
addonPath="$mountpoint/etc/options_menu/shonen"
countryCode="cst_cw"

cd "$addonPath"

echo "  ___                  _     "
echo " / __|_ __ _  _ _ _ __| |___ "
echo " \\__ \\ '_ \\ || | '_/ _\` / _ \\"
echo " |___/ .__/\\_,_|_| \\__,_\\___/"
echo "     |_|                     "
echo ""
echo "Translation: Scrubmacher"
echo "Shonen Jump Convertion: DefKorns"
echo ""
echo "Checking localization files."
wget -q --spider "$customLangURL"/$countryCode.tar.gz

if [ $? -eq 0 ]; then
echo "Downloading..."
wget "$customLangURL"/$countryCode.tar.gz

echo "Unpacking language..."
	tar -xzf $countryCode.tar.gz && rm -f ./*.tar.gz
    sleep 2
    echo "Complete."
	echo "Custom language now available and ready to use from the list."
else
   echo "Something may be wrong here."
   echo "Could not find the selected theme,"
   echo "check your internet connection. "
fi
