#!/bin/sh
source /etc/preinit
script_init


echo "  ___ _                        _                                        _  _         _   "
echo " / __| |_  ___ _ _  ___ _ _   | |   __ _ _ _  __ _ _  _ __ _ __ _ ___  | || |__ _ __| |__"
echo " \\__ \\ ' \\/ _ \\ ' \\/ -_) ' \\  | |__/ _\` | ' \\/ _\` | || / _\` / _\` / -_) | __ / _\` / _| / /"
echo " |___/_||_\\___/_||_\\___|_||_| |____\\__,_|_||_\\__, |\\_,_\\__,_\\__, \\___| |_||_\\__,_\\__|_\\_\\"
echo "                                             |___/          |___/                        "
echo ""
echo "HMOD by: Advokaten"
echo "Options Menu Scripts: DefKorns"
echo ""
echo "Translating to LANGUAGEHERE, please wait..."

countryCode="COUNTRYCODEHERE"
optionsDir="$mountpoint/etc/options_menu/languages"
commandsDir="$optionsDir/commands"

[ -f "$preinitpath/b8024_themeselector" ] && rm -f "$preinitpath/b8024_themeselector"
[ -f "$preinitpath/p8024_themeselector" ] && rm -f "$preinitpath/p8024_themeselector"
sed -r "s/CHANGE_ME/${countryCode}/g;" "$optionsDir/scripts/custom" >"$preinitpath/p8024_zlanguage"

customFont="$mountpoint/media/$modname/fonts"
	[ ! -d "$customFont" ] && customFont="$rootfs/usr/share/fonts"
[ ! -f "$customFont/title.backup" ] && cp -r "$customFont/title.fnt" "$customFont/title.backup"
cd "$customFont" && find . -type f -not -name 'title.*' -print0 -exec rm {} \;

cd "$optionsDir/custom_languages/fonts" && find . -iname "*.fnt" -exec cp -r {} "$customFont" \;


actiVe="$(grep -F " [X]" $commandsDir/* | cut -d : -f 1)"

if [ -f "$actiVe" ]; then
	sed -r -i 's/ \[X\]//g' $actiVe
	sed -r -i "1 s|$| [X]|" "$commandsDir/c0008_$countryCode"
else
	sed -r -i "1 s|$| [X]|" "$commandsDir/c0008_$countryCode"
fi
sleep 2

echo "COMMAND_NAME=Uninstall Custom languages
COMMAND_TYPE=INTERNAL
RESTART_UI=FALSE
COMMAND_STR=sh /etc/options_menu/languages/scripts/uninstall && usleep 50000 && hakchi reboot" > "$commandsDir/c8888_Uninstall"

sed -r "s/\/shonen//g;" "$optionsDir/shonen/scripts/jpn_ja" >"$optionsDir/scripts/uninstall"
