#!/bin/sh

source /etc/preinit
script_init

customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu"
optionsDir="$mountpoint/etc/options_menu/shonen"

cd "$optionsDir"
echo ""
echo "   ___        _               _                                        ___                  _              _         "
echo "  / __|  _ __| |_ ___ _ __   | |   __ _ _ _  __ _ _  _ __ _ __ _ ___  |   \\ _____ __ ___ _ | |___  __ _ __| |___ _ _ "
echo " | (_| || (_-<  _/ _ \\ '  \\  | |__/ _\` | ' \\/ _\` | || / _\` / _\` / -_) | |) / _ \\ V  V / ' \\| / _ \\/ _\` / _\` / -_) '_|"
echo "  \\___\\_,_/__/\\__\\___/_|_|_| |____\\__,_|_||_\\__, |\\_,_\\__,_\\__, \\___| |___/\\___/\\_/\\_/|_||_|_\\___/\\__,_\\__,_\\___|_|  "
echo "                                            |___/          |___/                                                     "
echo ""
echo "by DefKorns"
echo "Category: User Interface Mod "

echo "Checking available theme list"
wget -q --spider $customLangURL/localization.tar.gz

if [ $? -eq 0 ]; then
	echo ""
	echo "Downloading custom language list..."
	wget $customLangURL/localization.tar.gz
	echo ""
	echo "Updating language list."

	tar -xzf localization.tar.gz && rm -f *.tar.gz

	echo "Update complete."
else
	echo "Something may be wrong here."
	echo "Could not find any theme pack for Shonen Jump."
	echo "Please check your internet connection. "
fi
$mountpoint/etc/options_menu/options --commandPath $mountpoint/etc/options_menu/shonen/custom_languages/commands/ --scriptPath $mountpoint/etc/options_menu/shonen/custom_languages/scripts --title "Download Custom Languages" &
